services:
  postgres:
    image: postgres:15
    container_name: media-scorer-db
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-media_scoring}
      POSTGRES_USER: ${POSTGRES_USER:-media_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-media_password}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-media_user} -d ${POSTGRES_DB:-media_scoring}"]
      interval: 30s
      timeout: 10s
      retries: 5

  media-scorer:
    build: .
    container_name: media-scorer
    ports:
      - "${HOST_PORT:-7862}:${HOST_PORT:-7862}"
      - "${SSH_PORT:-2222}:22"
    volumes:
      - "${HOST_MEDIA_PATH}:/media"
      - ./config:/app/config
      - scores_data:/app/.scores
      - thumbnails_data:/app/.thumbnails
      - workflows_data:/app/.workflows
      - logs_data:/app/.logs
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - MEDIA_PATH=${MEDIA_PATH}
      - HOST_PORT=${HOST_PORT}
      - MEDIA_PATTERN=${MEDIA_PATTERN}
      - GENERATE_THUMBNAILS=${GENERATE_THUMBNAILS}
      - DATABASE_URL=${DATABASE_URL:-postgresql://${POSTGRES_USER:-media_user}:${POSTGRES_PASSWORD:-media_password}@postgres:5432/${POSTGRES_DB:-media_scoring}}
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data:
  scores_data:
  thumbnails_data:
  workflows_data:
  logs_data:
