dir: ./media                  # Default directory to scan
host: 127.0.0.1               # Host to bind the server
port: 7862                    # Port to serve
pattern: "*.mp4|*.png|*.jpg"  # Glob pattern for media files (e.g., *.mp4|*.png|*.jpg)
style: style_default.css   # CSS theme file (style_default.css, style_pastelcore.css, style_darkcandy.css)
generate_thumbnails: true     # Generate thumbnail previews for media files
thumbnail_height: 64          # Height in pixels for thumbnail previews
toggle_extensions: ["jpg", "png", "mp4"]  # File extensions for toggle buttons (default active extensions)
directory_sort_desc: true     # Sort directory dropdown in descending order (true) or ascending (false)

# Database settings for metadata storage and search functionality
enable_database: false          # Enable database storage for metadata and search features
database_path: null             # Custom database path (default: .scores/media.db in media directory)

# Database logging settings
enable_database_logging: true   # Enable detailed logging of all database interactions
database_log_dir: /app/.logs      # Directory for database interaction logs (daily rotation)
database_log_level: INFO        # Log level for database operations (DEBUG, INFO, WARNING, ERROR)

# Schema management settings
schema_file: schema.yml       # YAML file defining database schema structure
auto_migrate: false           # Automatically apply schema migrations (use with caution in production)
validate_schema: true         # Validate schema file on startup
